/****************************************************************************/
//    copyright 2010-2012 Chris Rizzitello <sithlord48@gmail.com>           //
//                                                                          //
//    This file is part of Black Chocobo.                                   //
//                                                                          //
//    Black Chocobo is free software: you can redistribute it and/or modify //
//    it under the terms of the GNU General Public License as published by  //
//    the Free Software Foundation, either version 3 of the License, or     //
//    (at your option) any later version.                                   //
//                                                                          //
//    Black Chocobo is distributed in the hope that it will be useful,      //
//    but WITHOUT ANY WARRANTY; without even the implied warranty of        //
//   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the          //
//    GNU General Public License for more details.                          //
/****************************************************************************/
#ifndef FF7STATICDATA_H
    #define FF7STATICDATA_H
#include <QObject>

struct LOCATION {//Location Table Stuff
    QString location;
    QString map_id;
    QString loc_id;
    QString x;
    QString y;
    QString z;
};
struct ITEM {
        QString name;
        QString image;
        qint8 mslots;
        qint8 linked;
};
struct MATERIA { //use MateriaNames,MateriaSkills or MateriaStats for text data.
    QString name;
    QString skills[5];
    QString stats;
    QString image;
    quint8 id;
    qint8 hp;
    qint8 mp;
    qint8 str;
    qint8 vit;
    qint8 dex;
    qint8 lck;
    qint8 mag;
    qint8 spi;//for use in hp/mp/char stat calculations (maybe later)
    qint32 ap[4];
    qint8 type; //1-magic,2-summon,3-independent,4-support,5-command,0-unknown
    qint8 levels;
};

class FF7StaticData
{
public:
    QString ItemNames(int);
    QString MateriaNames(int);
    QString MateriaStats(int);
    QString MateriaSkills(int,int);
    qint8 MateriaStats_Str(int);
    qint8 MateriaStats_Vit(int);
    qint8 MateriaStats_Mag(int);
    qint8 MateriaStats_Spi(int);
    qint8 MateriaStats_Dex(int);
    qint8 MateriaStats_Lck(int);
    qint8 MateriaStats_Hp(int);
    qint8 MateriaStats_Mp(int);
};

class locations
{
public:
    QString loc_name(int);
    QString map_id(int);
    QString loc_id(int);
    QString x(int);
    QString y(int);
    QString z(int);
    int len(void);
};
static LOCATION Locations[]=
{
    {QT_TRANSLATE_NOOP("Locations","Platform"),"1","116","3655","27432","25"},
    {QT_TRANSLATE_NOOP("Locations","Reactor No.1"),"1","124","37","1579","36"},
    {QT_TRANSLATE_NOOP("Locations","Reactor No. 5"),"1","128","64035","2546","20"},
    {QT_TRANSLATE_NOOP("Locations","Reactor No. 5"),"1","131","34","1617","36"},
    {QT_TRANSLATE_NOOP("Locations","Church in the slums"),"1","183","65463","400","8"},
    {QT_TRANSLATE_NOOP("Locations","Lower Sector 4 Plate"),"1","169","65422","468","11"},
    {QT_TRANSLATE_NOOP("Locations","Sector 5 - Slums"),"1","173","64997","135","78"},
    {QT_TRANSLATE_NOOP("Locations","Sector 7 - Slums"),"1","156","65185","636","231"},
    {QT_TRANSLATE_NOOP("Locations","7th Heaven"),"1","154","67","6","26"},
    {QT_TRANSLATE_NOOP("Locations","AVALANCHE Hideout"),"1","155","65346","65371","41"},
    {QT_TRANSLATE_NOOP("Locations","Midgar Sector 8"),"1","732","265","65332","24"},
    {QT_TRANSLATE_NOOP("Locations","Midgar Sector 8"),"1","739","61439","18394","34"},
    {QT_TRANSLATE_NOOP("Locations","Sector 8, Underground"),"1","733","65264","1614","116"},
    {QT_TRANSLATE_NOOP("Locations","Train Graveyard"),"1","144","1981","62327","71"},
    {QT_TRANSLATE_NOOP("Locations","Tunnel"),"1","736","65453","65237","215"},
    {QT_TRANSLATE_NOOP("Locations","Kalm Inn"),"1","332","267","65429","15"},
    {QT_TRANSLATE_NOOP("Locations","Aerith's House"),"1","187","175","65330","138"},
    {QT_TRANSLATE_NOOP("Locations","Beginner's Hall"),"1","149","220","65371","71"},
    {QT_TRANSLATE_NOOP("Locations","Wall Market"),"1","195","462","1080","58"},
    {QT_TRANSLATE_NOOP("Locations","Shinra Bldg."),"1","227","512","63074","105"},
    {QT_TRANSLATE_NOOP("Locations","Shinra Bldg 64F."),"1","247","64386","65253","245"},
    {QT_TRANSLATE_NOOP("Locations","Shinra Bldg 67F."),"1","256","65426","797","283"},
    {QT_TRANSLATE_NOOP("Locations","Shinra Bldg 69F."),"1","264","150","65102","226"},
    {QT_TRANSLATE_NOOP("Locations","Junon Inn"),"1","376","45","197","21"},
    {QT_TRANSLATE_NOOP("Locations","Junon Office F2"),"1","397","65162","65236","8"},
    {QT_TRANSLATE_NOOP("Locations","Junon Way"),"1","394","2184","64947","24"},
    {QT_TRANSLATE_NOOP("Locations","Junon Airport Path"),"1","386","64902","65203","31"},
    {QT_TRANSLATE_NOOP("Locations","Gaeas Cliff"),"1","699","65424","240","17"},
    {QT_TRANSLATE_NOOP("Locations","Gaeas Cliff"),"1","693","65384","1104","65"},
    {QT_TRANSLATE_NOOP("Locations","Gaeas Cliff Base"),"1","687","165","51","5"},
    {QT_TRANSLATE_NOOP("Locations","Mt. Nibel"),"1","317","667","65035","261"},
    {QT_TRANSLATE_NOOP("Locations","North Crater"),"1","749","65344","16","35"},
    {QT_TRANSLATE_NOOP("Locations","Corel Prison"),"1","473","876","1471","74"},
    {QT_TRANSLATE_NOOP("Locations","Fort Condor"),"1","355","1118","391","12"},
    {QT_TRANSLATE_NOOP("Locations","Underwater Reactor"),"1","422","34","426","14"},
    {QT_TRANSLATE_NOOP("Locations","Inside Submarine"),"1","408","65484","433","7"},
    {QT_TRANSLATE_NOOP("Locations","Hallway"),"1","88","65141","34","13"},
    {QT_TRANSLATE_NOOP("Locations","Cosmo Canyon"),"1","529","128","65215","79"},
    {QT_TRANSLATE_NOOP("Locations","Boat"),"1","436","65430","64368","46"},
    {QT_TRANSLATE_NOOP("Locations","Mt. Corel"),"1","462","63498","65531","220"},
    {QT_TRANSLATE_NOOP("Locations","Ropeway Station"),"1","496","64767","95","26"},
    {QT_TRANSLATE_NOOP("Locations","Forgotten Captial"),"1","633","65402","65401","40"},
    {QT_TRANSLATE_NOOP("Locations","Whirlwind Maze"),"1","703","65170","64488","44"},
    {QT_TRANSLATE_NOOP("Locations","Whirlwind Maze"),"1","705","94","1168","173"},
    {QT_TRANSLATE_NOOP("Locations","Wutai"),"1","579","64961","1101","34"},
    {QT_TRANSLATE_NOOP("Locations","Forgotten City"),"1","646","641","793","243"},
    {QT_TRANSLATE_NOOP("Locations","Chocobo Ranch"),"1","345","65535","64960","61"},
    {QT_TRANSLATE_NOOP("Locations","Highwind"),"1","72","65533","62949","99"},
    {QT_TRANSLATE_NOOP("Locations","Debug Room [en]"),"1","94","0","0","0"},
    {QT_TRANSLATE_NOOP("Locations","Debug Room [ja]"),"1","65","0","0","0"},
    {QT_TRANSLATE_NOOP("Locations","Test Fight"),"2","0","0","0","0"}
};
static ITEM Items[]=
{
    {QT_TRANSLATE_NOOP("Items","Potion"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Hi-Potion"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","X-Potion"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Ether"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Turbo Ether"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Elixir"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Megalixir"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Phoenix Down"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Antidote"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Soft"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Maiden's Kiss"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Cornucopia"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Echo screen"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Hyper"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Tranquilizer"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Remedy"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Smoke Bomb"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Speed Drink"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Hero Drink"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Vaccine"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Grenade"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Shrapnel"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Right arm"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Hourglass"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Kiss of Death"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Spider Web"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Dream Powder"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Mute Mask"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","War Gong"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Loco weed"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Fire Fang"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Fire Veil"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Antarctic Wind"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Ice Crystal"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Bolt Plume"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Swift Bolt"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Earth Drum"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Earth Mallet"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Deadly Waste"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","M-Tentacles"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Stardust"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Vampire Fang"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Ghost Hand"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Vagyrisk Claw"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Light Curtain"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Lunar Curtain"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Mirror"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Holy Torch"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Bird Wing"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Dragon Scales"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Impaler"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Shrivel"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Eye drop"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Molotov"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","S-mine"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","8-inch Cannon"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Graviball"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","T/S Bomb"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Ink"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Dazers"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Dragon Fang"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Cauldron"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Sylkis Greens"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Reagan Greens"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Mimett Greens"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Curiel Greens"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Pahsana Greens"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Tantal Greens"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Krakka Greens"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Gysahl Greens"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Tent"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Power Source"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Guard Source"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Magic Source"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Mind Source"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Speed Source"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Luck Source"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Zeio Nut"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Carob Nut"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Porov Nut"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Pram Nut"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Lasan Nut"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Saraha Nut"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Luchile Nut"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Pepio Nut"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Battery"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Tissue"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Omnislash"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Catastrophe"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Final Heaven"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Great Gospel"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Cosmo Memory"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","All Creation"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Chaos"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Highwind"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","1/35 soldier"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Super Sweeper"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Masamune Blade"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Save Crystal"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Combat Diary"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Autograph"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Gambler"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Desert Rose"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Earth Harp"),":/icon/item",0,0},
    {QT_TRANSLATE_NOOP("Items","Guide Book"),":/icon/item",0,0},
  //nothing 106-127
    {QT_TRANSLATE_NOOP("Items","DON'T USE"),'\0',0,0},
    {QT_TRANSLATE_NOOP("Items","DON'T USE"),'\0',0,0},
    {QT_TRANSLATE_NOOP("Items","DON'T USE"),'\0',0,0},
    {QT_TRANSLATE_NOOP("Items","DON'T USE"),'\0',0,0},
    {QT_TRANSLATE_NOOP("Items","DON'T USE"),'\0',0,0},
    {QT_TRANSLATE_NOOP("Items","DON'T USE"),'\0',0,0},
    {QT_TRANSLATE_NOOP("Items","DON'T USE"),'\0',0,0},
    {QT_TRANSLATE_NOOP("Items","DON'T USE"),'\0',0,0},
    {QT_TRANSLATE_NOOP("Items","DON'T USE"),'\0',0,0},
    {QT_TRANSLATE_NOOP("Items","DON'T USE"),'\0',0,0},
    {QT_TRANSLATE_NOOP("Items","DON'T USE"),'\0',0,0},
    {QT_TRANSLATE_NOOP("Items","DON'T USE"),'\0',0,0},
    {QT_TRANSLATE_NOOP("Items","DON'T USE"),'\0',0,0},
    {QT_TRANSLATE_NOOP("Items","DON'T USE"),'\0',0,0},
    {QT_TRANSLATE_NOOP("Items","DON'T USE"),'\0',0,0},
    {QT_TRANSLATE_NOOP("Items","DON'T USE"),'\0',0,0},
    {QT_TRANSLATE_NOOP("Items","DON'T USE"),'\0',0,0},
    {QT_TRANSLATE_NOOP("Items","DON'T USE"),'\0',0,0},
    {QT_TRANSLATE_NOOP("Items","DON'T USE"),'\0',0,0},
    {QT_TRANSLATE_NOOP("Items","DON'T USE"),'\0',0,0},
    {QT_TRANSLATE_NOOP("Items","DON'T USE"),'\0',0,0},
    {QT_TRANSLATE_NOOP("Items","DON'T USE"),'\0',0,0},
    {QT_TRANSLATE_NOOP("Items","DON'T USE"),'\0',0,0},
   //cloud weapons 128 -143
   {QT_TRANSLATE_NOOP("Items","Buster Sword"),":/icon/cloud_weapon",2,1},
   {QT_TRANSLATE_NOOP("Items","Mythril Saber"),":/icon/cloud_weapon",3,1},
   {QT_TRANSLATE_NOOP("Items","Hardedge"),":/icon/cloud_weapon",4,1},
   {QT_TRANSLATE_NOOP("Items","Butterfly Edge"),":/icon/cloud_weapon",4,2},
   {QT_TRANSLATE_NOOP("Items","Enhance Sword"),":/icon/cloud_weapon",8,4},
   {QT_TRANSLATE_NOOP("Items","Organics"),":/icon/cloud_weapon",6,2},
   {QT_TRANSLATE_NOOP("Items","Crystal Sword"),":/icon/cloud_weapon",6,3},
   {QT_TRANSLATE_NOOP("Items","Force Stealer"),":/icon/cloud_weapon",3,0},
   {QT_TRANSLATE_NOOP("Items","Rune Blade"),":/icon/cloud_weapon",4,0},
   {QT_TRANSLATE_NOOP("Items","Murasame"),":/icon/cloud_weapon",5,2},
   {QT_TRANSLATE_NOOP("Items","Nail Bat"),":/icon/cloud_weapon",0,0},
   {QT_TRANSLATE_NOOP("Items","Yoshiyuki"),":/icon/cloud_weapon",2,0},
   {QT_TRANSLATE_NOOP("Items","Apocalypse"),":/icon/cloud_weapon",3,0},
   {QT_TRANSLATE_NOOP("Items","Heaven's Cloud"),":/icon/cloud_weapon",6,0},
   {QT_TRANSLATE_NOOP("Items","Ragnarok"),":/icon/cloud_weapon",6,3},
   {QT_TRANSLATE_NOOP("Items","Ultima Weapon"),":/icon/cloud_weapon",8,4},
   ///tifa's weapons 144-159/tifa's weapons 144-159
   {QT_TRANSLATE_NOOP("Items","Leather Glove"),":/icon/tifa_weapon",1,0},
   {QT_TRANSLATE_NOOP("Items","Metal Knuckle"),":/icon/tifa_weapon",2,1},
   {QT_TRANSLATE_NOOP("Items","Mythril Claw"),":/icon/tifa_weapon",3,1},
   {QT_TRANSLATE_NOOP("Items","Grand Glove"),":/icon/tifa_weapon",4,1},
   {QT_TRANSLATE_NOOP("Items","Tiger Fang"),":/icon/tifa_weapon",4,2},
   {QT_TRANSLATE_NOOP("Items","Diamond Knuckle"),":/icon/tifa_weapon",5,2},
   {QT_TRANSLATE_NOOP("Items","Dragon Claw"),":/icon/tifa_weapon",6,2},
   {QT_TRANSLATE_NOOP("Items","Crystal Glove"),":/icon/tifa_weapon",6,3},
   {QT_TRANSLATE_NOOP("Items","Motor Drive"),":/icon/tifa_weapon",3,0},
   {QT_TRANSLATE_NOOP("Items","Platinum Fist"),":/icon/tifa_weapon",4,0},
   {QT_TRANSLATE_NOOP("Items","Kaiser Knuckle"),":/icon/tifa_weapon",8,1},
   {QT_TRANSLATE_NOOP("Items","Work Glove"),":/icon/tifa_weapon",0,0},
   {QT_TRANSLATE_NOOP("Items","Powersoul"),":/icon/tifa_weapon",4,0},
   {QT_TRANSLATE_NOOP("Items","Master Fist"),":/icon/tifa_weapon",6,0},
   {QT_TRANSLATE_NOOP("Items","God's Hand"),":/icon/tifa_weapon",4,2},
   {QT_TRANSLATE_NOOP("Items","Premium Heart"),":/icon/tifa_weapon",8,4},
   //barret's weapons 160-175
   {QT_TRANSLATE_NOOP("Items","Gatling Gun"),":/icon/barret_weapon",1,0},
   {QT_TRANSLATE_NOOP("Items","Assault Gun"),":/icon/barret_weapon",2,1},
   {QT_TRANSLATE_NOOP("Items","Cannon Ball"),":/icon/barret_weapon",3,1},
   {QT_TRANSLATE_NOOP("Items","Atomic Scissors"),":/icon/barret_weapon",4,2},
   {QT_TRANSLATE_NOOP("Items","Heavy Vulcan"),":/icon/barret_weapon",4,2},
   {QT_TRANSLATE_NOOP("Items","Chainsaw"),":/icon/barret_weapon",5,2},
   {QT_TRANSLATE_NOOP("Items","Microlaser"),":/icon/barret_weapon",6,2},
   {QT_TRANSLATE_NOOP("Items","A M Cannon"),":/icon/barret_weapon",6,3},
   {QT_TRANSLATE_NOOP("Items","W Machine Gun"),":/icon/barret_weapon",3,0},
   {QT_TRANSLATE_NOOP("Items","Drill Arm"),":/icon/barret_weapon",4,0},
   {QT_TRANSLATE_NOOP("Items","Solid Bazooka"),":/icon/barret_weapon",8,4},
   {QT_TRANSLATE_NOOP("Items","Rocket Punch"),":/icon/barret_weapon",0,0},
   {QT_TRANSLATE_NOOP("Items","Enemy Launcher"),":/icon/barret_weapon",5,1},
   {QT_TRANSLATE_NOOP("Items","Pile Banger"),":/icon/barret_weapon",6,3},
   {QT_TRANSLATE_NOOP("Items","Max Ray"),":/icon/barret_weapon",6,3},
   {QT_TRANSLATE_NOOP("Items","Missing Score"),":/icon/barret_weapon",8,4},
   //red's weapons 176-189
   {QT_TRANSLATE_NOOP("Items","Mythril Clip"),":/icon/red_weapon",3,1},
   {QT_TRANSLATE_NOOP("Items","Diamond Pin"),":/icon/red_weapon",4,1},
   {QT_TRANSLATE_NOOP("Items","Silver Barette"),":/icon/red_weapon",4,2},
   {QT_TRANSLATE_NOOP("Items","Gold Barette"),":/icon/red_weapon",5,2},
   {QT_TRANSLATE_NOOP("Items","Adaman Clip"),":/icon/red_weapon",6,2},
   {QT_TRANSLATE_NOOP("Items","Crystal Comb"),":/icon/red_weapon",6,3},
   {QT_TRANSLATE_NOOP("Items","Magic Comb"),":/icon/red_weapon",3,0},
   {QT_TRANSLATE_NOOP("Items","Plus Barrette"),":/icon/red_weapon",4,0},
   {QT_TRANSLATE_NOOP("Items","Centclip"),":/icon/red_weapon",8,0},
   {QT_TRANSLATE_NOOP("Items","Hairpin"),":/icon/red_weapon",0,0},
   {QT_TRANSLATE_NOOP("Items","Seraph Comb"),":/icon/red_weapon",4,0},
   {QT_TRANSLATE_NOOP("Items","Behemoth Horn"),":/icon/red_weapon",6,0},
   {QT_TRANSLATE_NOOP("Items","Spring Gun Clip"),":/icon/red_weapon",6,3},
   {QT_TRANSLATE_NOOP("Items","Limited Moon"),":/icon/red_weapon",8,4},
   //aeris weapons 190-200
   {QT_TRANSLATE_NOOP("Items","Guard Stick"),":/icon/aeris_weapon",2,1},
   {QT_TRANSLATE_NOOP("Items","Mythril Rod"),":/icon/aeris_weapon",3,1},
   {QT_TRANSLATE_NOOP("Items","Full Metal Staff"),":/icon/aeris_weapon",3,1},
   {QT_TRANSLATE_NOOP("Items","Striking Staff"),":/icon/aeris_weapon",4,1},
   {QT_TRANSLATE_NOOP("Items","Prism Staff"),":/icon/aeris_weapon",4,2},
   {QT_TRANSLATE_NOOP("Items","Aurora Rod"),":/icon/aeris_weapon",5,2},
   {QT_TRANSLATE_NOOP("Items","Wizard Staff"),":/icon/aeris_weapon",3,0},
   {QT_TRANSLATE_NOOP("Items","Wizer Staff"),":/icon/aeris_weapon",4,0},
   {QT_TRANSLATE_NOOP("Items","Fairy Tale"),":/icon/aeris_weapon",7,0},
   {QT_TRANSLATE_NOOP("Items","Umbrella"),":/icon/aeris_weapon",0,0},
   {QT_TRANSLATE_NOOP("Items","Princess Guard"),":/icon/aeris_weapon",7,3},
   //cid weapons 201-214
   {QT_TRANSLATE_NOOP("Items","Spear"),":/icon/cid_weapon",1,0},
   {QT_TRANSLATE_NOOP("Items","Slash Lance"),":/icon/cid_weapon",5,2},
   {QT_TRANSLATE_NOOP("Items","Trident"),":/icon/cid_weapon",6,0},
   {QT_TRANSLATE_NOOP("Items","Mast Ax"),":/icon/cid_weapon",6,2},
   {QT_TRANSLATE_NOOP("Items","Partisan"),":/icon/cid_weapon",6,3},
   {QT_TRANSLATE_NOOP("Items","Viper Halberd"),":/icon/cid_weapon",4,0},
   {QT_TRANSLATE_NOOP("Items","Javelin"),":/icon/cid_weapon",5,2},
   {QT_TRANSLATE_NOOP("Items","Grow Lance"),":/icon/cid_weapon",6,3},
   {QT_TRANSLATE_NOOP("Items","Mop"),":/icon/cid_weapon",0,0},
   {QT_TRANSLATE_NOOP("Items","Dragoon Lance"),":/icon/cid_weapon",8,0},
   {QT_TRANSLATE_NOOP("Items","Scimitar"),":/icon/cid_weapon",2,1},
   {QT_TRANSLATE_NOOP("Items","Flayer"),":/icon/cid_weapon",6,0},
   {QT_TRANSLATE_NOOP("Items","Spirit Lance"),":/icon/cid_weapon",4,2},
   {QT_TRANSLATE_NOOP("Items","Venus Gospel"),":/icon/cid_weapon",8,4},
   //yuffie weapons 215-228
   {QT_TRANSLATE_NOOP("Items","4-point Shuriken"),":/icon/yuffie_weapon",3,1},
   {QT_TRANSLATE_NOOP("Items","Boomerang"),":/icon/yuffie_weapon",4,1},
   {QT_TRANSLATE_NOOP("Items","Pinwheel"),":/icon/yuffie_weapon",4,2},
   {QT_TRANSLATE_NOOP("Items","Razor Ring"),":/icon/yuffie_weapon",5,2},
   {QT_TRANSLATE_NOOP("Items","Hawkeye"),":/icon/yuffie_weapon",6,2},
   {QT_TRANSLATE_NOOP("Items","Crystal Cross"),":/icon/yuffie_weapon",6,3},
   {QT_TRANSLATE_NOOP("Items","Wind Slash"),":/icon/yuffie_weapon",3,0},
   {QT_TRANSLATE_NOOP("Items","Twin Viper"),":/icon/yuffie_weapon",4,0},
   {QT_TRANSLATE_NOOP("Items","Spiral Shuriken"),":/icon/yuffie_weapon",8,1},
   {QT_TRANSLATE_NOOP("Items","Superball"),":/icon/yuffie_weapon",0,0},
   {QT_TRANSLATE_NOOP("Items","Magic Shuriken"),":/icon/yuffie_weapon",3,0},
   {QT_TRANSLATE_NOOP("Items","Rising Sun"),":/icon/yuffie_weapon",4,2},
   {QT_TRANSLATE_NOOP("Items","Oritsuru"),":/icon/yuffie_weapon",8,2},
   {QT_TRANSLATE_NOOP("Items","Conformer"),":/icon/yuffie_weapon",8,4},
   //cait sith weapons 229-241
   {QT_TRANSLATE_NOOP("Items","Yellow M-phone"),":/icon/cait_weapon",4,2},
   {QT_TRANSLATE_NOOP("Items","Green M-phone"),":/icon/cait_weapon",4,2},
   {QT_TRANSLATE_NOOP("Items","Blue M-phone"),":/icon/cait_weapon",5,2},
   {QT_TRANSLATE_NOOP("Items","Red M-phone"),":/icon/cait_weapon",6,2},
   {QT_TRANSLATE_NOOP("Items","Crystal M-phone"),":/icon/cait_weapon",6,3},
   {QT_TRANSLATE_NOOP("Items","White M-phone"),":/icon/cait_weapon",3,0},
   {QT_TRANSLATE_NOOP("Items","Black M-phone"),":/icon/cait_weapon",4,0},
   {QT_TRANSLATE_NOOP("Items","Silver M-phone"),":/icon/cait_weapon",8,0},
   {QT_TRANSLATE_NOOP("Items","Trumpet Shell"),":/icon/cait_weapon",0,0},
   {QT_TRANSLATE_NOOP("Items","Gold M-phone"),":/icon/cait_weapon",8,4},
   {QT_TRANSLATE_NOOP("Items","Battle Trumpet"),":/icon/cait_weapon",6,3},
   {QT_TRANSLATE_NOOP("Items","Starlight Phone"),":/icon/cait_weapon",8,4},
   {QT_TRANSLATE_NOOP("Items","HP Shout"),":/icon/cait_weapon",8,4},
   //vincent weapons... 242-254
   {QT_TRANSLATE_NOOP("Items","Quicksilver"),":/icon/vincent_weapon",4,1},
   {QT_TRANSLATE_NOOP("Items","Shotgun"),":/icon/vincent_weapon",4,1},
   {QT_TRANSLATE_NOOP("Items","Shortbarrel"),":/icon/vincent_weapon",5,2},
   {QT_TRANSLATE_NOOP("Items","Lariat"),":/icon/vincent_weapon",6,2},
   {QT_TRANSLATE_NOOP("Items","Winchester"),":/icon/vincent_weapon",6,3},
   {QT_TRANSLATE_NOOP("Items","Peacemaker"),":/icon/vincent_weapon",3,1},
   {QT_TRANSLATE_NOOP("Items","Buntline"),":/icon/vincent_weapon",4,2},
   {QT_TRANSLATE_NOOP("Items","Long Barrel R"),":/icon/vincent_weapon",8,4},
   {QT_TRANSLATE_NOOP("Items","Silver Rifle"),":/icon/vincent_weapon",0,0},
   {QT_TRANSLATE_NOOP("Items","Sniper CR"),":/icon/vincent_weapon",4,2},
   {QT_TRANSLATE_NOOP("Items","Supershot ST"),":/icon/vincent_weapon",6,3},
   {QT_TRANSLATE_NOOP("Items","Outsider"),":/icon/vincent_weapon",8,2},
   {QT_TRANSLATE_NOOP("Items","Death Penalty"),":/icon/vincent_weapon",8,4},
   //sepi weapon =255
   {QT_TRANSLATE_NOOP("Items","Masamune"),":/icon/item",5,2},
   //armor  256-287
   {QT_TRANSLATE_NOOP("Items","Bronze Bangle"),":/icon/armor",0,0},
   {QT_TRANSLATE_NOOP("Items","Iron Bangle"),":/icon/armor",1,0},
   {QT_TRANSLATE_NOOP("Items","Titan Bangle"),":/icon/armor",2,0},
   {QT_TRANSLATE_NOOP("Items","Mythril Armlet"),":/icon/armor",2,1},
   {QT_TRANSLATE_NOOP("Items","Carbon Bangle"),":/icon/armor",3,1},
   {QT_TRANSLATE_NOOP("Items","Silver Armlet"),":/icon/armor",4,1},
   {QT_TRANSLATE_NOOP("Items","Gold Armlet"),":/icon/armor",4,2},
   {QT_TRANSLATE_NOOP("Items","Diamond Bangle"),":/icon/armor",5,2},
   {QT_TRANSLATE_NOOP("Items","Crystal Bangle"),":/icon/armor",6,3},
   {QT_TRANSLATE_NOOP("Items","Platinum Bangle"),":/icon/armor",2,0},
   {QT_TRANSLATE_NOOP("Items","Rune Armlet"),":/icon/armor",4,0},
   {QT_TRANSLATE_NOOP("Items","Edincoat"),":/icon/armor",7,0},
   {QT_TRANSLATE_NOOP("Items","Wizard Bracelet"),":/icon/armor",8,4},
   {QT_TRANSLATE_NOOP("Items","Adaman Bangle"),":/icon/armor",2,1},
   {QT_TRANSLATE_NOOP("Items","Gigas Armlet"),":/icon/armor",5,2},
   {QT_TRANSLATE_NOOP("Items","Imperial Guard"),":/icon/armor",6,3},
   {QT_TRANSLATE_NOOP("Items","Aegis Armlet"),":/icon/armor",4,2},
   {QT_TRANSLATE_NOOP("Items","Fourth Bracelet"),":/icon/armor",5,2},
   {QT_TRANSLATE_NOOP("Items","Warrior Bangle"),":/icon/armor",4,2},
   {QT_TRANSLATE_NOOP("Items","Shinra Beta"),":/icon/armor",4,1},
   {QT_TRANSLATE_NOOP("Items","Shinra Alpha"),":/icon/armor",6,3},
   {QT_TRANSLATE_NOOP("Items","Four Slots"),":/icon/armor",4,0},
   {QT_TRANSLATE_NOOP("Items","Fire Armlet"),":/icon/armor",4,2},
   {QT_TRANSLATE_NOOP("Items","Aurora Armlet"),":/icon/armor",4,2},
   {QT_TRANSLATE_NOOP("Items","Bolt Armlet"),":/icon/armor",4,2},
   {QT_TRANSLATE_NOOP("Items","Dragon Armlet"),":/icon/armor",6,3},
   {QT_TRANSLATE_NOOP("Items","Minerva Band"),":/icon/armor",6,3},
   {QT_TRANSLATE_NOOP("Items","Escort Guard"),":/icon/armor",6,3},
   {QT_TRANSLATE_NOOP("Items","Mystile"),":/icon/armor",6,3},
   {QT_TRANSLATE_NOOP("Items","Ziedrich"),":/icon/armor",0,0},
   {QT_TRANSLATE_NOOP("Items","Precious Watch"),":/icon/armor",8,0},
   {QT_TRANSLATE_NOOP("Items","Chocobracelet"),":/icon/armor",4,0},
   //accessorys 288-319
   {QT_TRANSLATE_NOOP("Items","Power Wrist"),":/icon/accessory",0,0},
   {QT_TRANSLATE_NOOP("Items","Protect Vest"),":/icon/accessory",0,0},
   {QT_TRANSLATE_NOOP("Items","Earring"),":/icon/accessory",0,0},
   {QT_TRANSLATE_NOOP("Items","Talisman"),":/icon/accessory",0,0},
   {QT_TRANSLATE_NOOP("Items","Choco Feather"),":/icon/accessory",0,0},
   {QT_TRANSLATE_NOOP("Items","Amulet"),":/icon/accessory",0,0},
   {QT_TRANSLATE_NOOP("Items","Champion Belt"),":/icon/accessory",0,0},
   {QT_TRANSLATE_NOOP("Items","Poison Ring"),":/icon/accessory",0,0},
   {QT_TRANSLATE_NOOP("Items","Tough Ring"),":/icon/accessory",0,0},
   {QT_TRANSLATE_NOOP("Items","Circlet"),":/icon/accessory",0,0},
   {QT_TRANSLATE_NOOP("Items","Star Pendant"),":/icon/accessory",0,0},
   {QT_TRANSLATE_NOOP("Items","Silver Glasses"),":/icon/accessory",0,0},
   {QT_TRANSLATE_NOOP("Items","Headband"),":/icon/accessory",0,0},
   {QT_TRANSLATE_NOOP("Items","Fairy Ring"),":/icon/accessory",0,0},
   {QT_TRANSLATE_NOOP("Items","Jem Ring"),":/icon/accessory",0,0},
   {QT_TRANSLATE_NOOP("Items","White Cape"),":/icon/accessory",0,0},
   {QT_TRANSLATE_NOOP("Items","Sprint Shoes"),":/icon/accessory",0,0},
   {QT_TRANSLATE_NOOP("Items","Peace Ring"),":/icon/accessory",0,0},
   {QT_TRANSLATE_NOOP("Items","Ribbon"),":/icon/accessory",0,0},
   {QT_TRANSLATE_NOOP("Items","Fire Ring"),":/icon/accessory",0,0},
   {QT_TRANSLATE_NOOP("Items","Ice Ring"),":/icon/accessory",0,0},
   {QT_TRANSLATE_NOOP("Items","Bolt Ring"),":/icon/accessory",0,0},
   {QT_TRANSLATE_NOOP("Items","Tetra Elemental"),":/icon/accessory",0,0},
   {QT_TRANSLATE_NOOP("Items","Safety Bit"),":/icon/accessory",0,0},
   {QT_TRANSLATE_NOOP("Items","Fury Ring"),":/icon/accessory",0,0},
   {QT_TRANSLATE_NOOP("Items","Curse Ring"),":/icon/accessory",0,0},
   {QT_TRANSLATE_NOOP("Items","Protect Ring"),":/icon/accessory",0,0},
   {QT_TRANSLATE_NOOP("Items","Cat's Bell"),":/icon/accessory",0,0},
   {QT_TRANSLATE_NOOP("Items","Reflect Ring"),":/icon/accessory",0,0},
   {QT_TRANSLATE_NOOP("Items","Water Ring"),":/icon/accessory",0,0},
   {QT_TRANSLATE_NOOP("Items","Sneak Glove"),":/icon/accessory",0,0},
   {QT_TRANSLATE_NOOP("Items","HypnoCrown"),":/icon/accessory",0,0}
};



static MATERIA Materias[]=
{
    {QT_TRANSLATE_NOOP("Materia_Names","MP Plus"),         {QT_TRANSLATE_NOOP("Materia_Skills","MP Plus +10%"),QT_TRANSLATE_NOOP("Materia_Skills","MP Plus +20%"),QT_TRANSLATE_NOOP("Materia_Skills","MP Plus +30%"),QT_TRANSLATE_NOOP("Materia_Skills","MP Plus +40%"),QT_TRANSLATE_NOOP("Materia_Skills","MP Plus +50%")},QT_TRANSLATE_NOOP("Materia_Stats","MaxMp:+% depending on level"), ":/icon/independent", 0x00,0,0,0,0,0,0,0,0,{10000,20000,30000,50000},3,5},
    {QT_TRANSLATE_NOOP("Materia_Names","HP Plus"),         {QT_TRANSLATE_NOOP("Materia_Skills","HP Plus +10%"),QT_TRANSLATE_NOOP("Materia_Skills","HP Plus +20%"),QT_TRANSLATE_NOOP("Materia_Skills","HP Plus +30%"),QT_TRANSLATE_NOOP("Materia_Skills","HP Plus +40%"),QT_TRANSLATE_NOOP("Materia_Skills","HP Plus +50%")},QT_TRANSLATE_NOOP("Materia_Stats","MaxHp:+% depending on level"), ":/icon/independent", 0x01,0,0,0,0,0,0,0,0,{10000,20000,30000,50000},3,5},
    {QT_TRANSLATE_NOOP("Materia_Names","Speed Plus"),      {QT_TRANSLATE_NOOP("Materia_Skills","Speed Plus +10%"),QT_TRANSLATE_NOOP("Materia_Skills","Speed Plus +20%"),QT_TRANSLATE_NOOP("Materia_Skills","Speed Plus +30%"),QT_TRANSLATE_NOOP("Materia_Skills","Speed Plus +40%"),QT_TRANSLATE_NOOP("Materia_Skills","Speed Plus +50%")},QT_TRANSLATE_NOOP("Materia_Stats","Dex:+% depending on level"), ":/icon/independent", 0x02,0,0,0,0,0,0,0,0,{15000,30000,60000,100000},3,5},
    {QT_TRANSLATE_NOOP("Materia_Names","Magic Plus"),      {QT_TRANSLATE_NOOP("Materia_Skills","Magic Plus +10%"),QT_TRANSLATE_NOOP("Materia_Skills","Magic Plus +20%"),QT_TRANSLATE_NOOP("Materia_Skills","Magic Plus +30%"),QT_TRANSLATE_NOOP("Materia_Skills","Magic Plus +40%"),QT_TRANSLATE_NOOP("Materia_Skills","Magic Plus +50%")},QT_TRANSLATE_NOOP("Materia_Stats","Mag:+% depending on level"), ":/icon/independent", 0x03,0,0,0,0,0,0,0,0,{10000,20000,30000,50000},3,5},
    {QT_TRANSLATE_NOOP("Materia_Names","Luck Plus"),       {QT_TRANSLATE_NOOP("Materia_Skills","Luck Plus +10%"),QT_TRANSLATE_NOOP("Materia_Skills","Luck Plus +20%"),QT_TRANSLATE_NOOP("Materia_Skills","Luck Plus +30%"),QT_TRANSLATE_NOOP("Materia_Skills","Luck Plus +40%"),QT_TRANSLATE_NOOP("Materia_Skills","Luck Plus +50%")},QT_TRANSLATE_NOOP("Materia_Stats","Lck:+% depending on level"), ":/icon/independent", 0x04,0,0,0,0,0,0,0,0,{15000,30000,60000,100000},3,5},
    {QT_TRANSLATE_NOOP("Materia_Names","EXP Plus"),        {QT_TRANSLATE_NOOP("Materia_Skills","Exp Plus +50%"),QT_TRANSLATE_NOOP("Materia_Skills","Exp Plus +100%"),QT_TRANSLATE_NOOP("Materia_Skills",""),"",""},QT_TRANSLATE_NOOP("Materia_Stats","Lck:+1"), ":/icon/independent", 0x05,0,0,0,0,0,+1,0,0,{60000,150000,0,0},3,3},
    {QT_TRANSLATE_NOOP("Materia_Names","Gil Plus"),        {QT_TRANSLATE_NOOP("Materia_Skills","Gil Plus +50%"),QT_TRANSLATE_NOOP("Materia_Skills","Gil Plus +100%"),QT_TRANSLATE_NOOP("Materia_Skills",""),"",""},QT_TRANSLATE_NOOP("Materia_Stats","Lck:+1"), ":/icon/independent", 0x06,0,0,0,0,0,+1,0,0,{80000,150000,0,0},3,3},
    {QT_TRANSLATE_NOOP("Materia_Names","Enemy Away"),      {QT_TRANSLATE_NOOP("Materia_Skills","Encounter Rate -50%"),QT_TRANSLATE_NOOP("Materia_Skills","Encounter Rate -75%"),QT_TRANSLATE_NOOP("Materia_Skills",""),"",""},QT_TRANSLATE_NOOP("Materia_Stats","Lck:+1"), ":/icon/independent", 0x07,0,0,0,0,0,+1,0,0,{10000,50000,0,0},3,3},
    {QT_TRANSLATE_NOOP("Materia_Names","Enemy Lure"),      {QT_TRANSLATE_NOOP("Materia_Skills","Encounter Rate +50%"),QT_TRANSLATE_NOOP("Materia_Skills","Encounter Rate +100%"),QT_TRANSLATE_NOOP("Materia_Skills",""),"",""},QT_TRANSLATE_NOOP("Materia_Stats","Lck:-1"), ":/icon/independent", 0x08,0,0,0,0,0,-1,0,0,{10000,50000,0,0},3,3},
    {QT_TRANSLATE_NOOP("Materia_Names","Chocobo Lure"),    {QT_TRANSLATE_NOOP("Materia_Skills","Chocobo Lure"),QT_TRANSLATE_NOOP("Materia_Skills","Chocobo Lure +50%"),QT_TRANSLATE_NOOP("Materia_Skills","Chocobo Lure +100%"),QT_TRANSLATE_NOOP("Materia_Skills","Chocobo Lure +200%"),QT_TRANSLATE_NOOP("Materia_Skills","")},QT_TRANSLATE_NOOP("Materia_Stats","Lck:+1"), ":/icon/independent", 0x09,0,0,0,0,0,+1,0,0,{3000,10000,30000,0},3,4},
    {QT_TRANSLATE_NOOP("Materia_Names","Pre-emptive"),     {QT_TRANSLATE_NOOP("Materia_Skills","Pre-emptive +6%"),QT_TRANSLATE_NOOP("Materia_Skills","Pre-emptive +12%"),QT_TRANSLATE_NOOP("Materia_Skills","Pre-emptive +24%"),QT_TRANSLATE_NOOP("Materia_Skills","Pre-emptive +36%"),QT_TRANSLATE_NOOP("Materia_Skills","Pre-emptive +48%")},QT_TRANSLATE_NOOP("Materia_Stats","Dex:+2"), ":/icon/independent", 0x0A,0,0,0,0,+2,0,0,0,{8000,20000,40000,80000},3,5},
    {QT_TRANSLATE_NOOP("Materia_Names","Long Range"),      {QT_TRANSLATE_NOOP("Materia_Skills","Long Range"),QT_TRANSLATE_NOOP("Materia_Skills",""),"","",""},"", ":/icon/independent", 0x0B,0,0,0,0,0,0,0,0,{80000,0,0,0},3,2},
    {QT_TRANSLATE_NOOP("Materia_Names","Mega All"),        {QT_TRANSLATE_NOOP("Materia_Skills","Mega-all x1"),QT_TRANSLATE_NOOP("Materia_Skills","Mega-all x2"),QT_TRANSLATE_NOOP("Materia_Skills","Mega-all x3"),QT_TRANSLATE_NOOP("Materia_Skills","Mega-all x4"),QT_TRANSLATE_NOOP("Materia_Skills","Mega-all x5")},"", ":/icon/independent", 0x0C,0,0,0,0,0,0,0,0,{20000,40000,80000,160000},3,5},
    {QT_TRANSLATE_NOOP("Materia_Names","Counter Attack"),  {QT_TRANSLATE_NOOP("Materia_Skills","Counter Attack 20%"),QT_TRANSLATE_NOOP("Materia_Skills","Counter Attack 40%"),QT_TRANSLATE_NOOP("Materia_Skills","Counter Attack 60%"),QT_TRANSLATE_NOOP("Materia_Skills","Counter Attack 80%"),QT_TRANSLATE_NOOP("Materia_Skills","Counter Attack 100%")},"", ":/icon/independent", 0x0D,0,0,0,0,0,0,0,0,{10000,20000,50000,100000},3,5},
    {QT_TRANSLATE_NOOP("Materia_Names","Slash-All"),       {QT_TRANSLATE_NOOP("Materia_Skills","Slash-All"),QT_TRANSLATE_NOOP("Materia_Skills","Flash"),QT_TRANSLATE_NOOP("Materia_Skills",""),"",""},"", ":/icon/command",     0x0E,0,0,0,0,0,0,0,0,{130000,150000,0,0},5,3},
    {QT_TRANSLATE_NOOP("Materia_Names","Double Cut"),      {QT_TRANSLATE_NOOP("Materia_Skills","2x-Cut"),QT_TRANSLATE_NOOP("Materia_Skills","4x-Cut"),QT_TRANSLATE_NOOP("Materia_Skills",""),"",""},QT_TRANSLATE_NOOP("Materia_Stats","Dex:+2"), ":/icon/command",     0x0F,0,0,0,0,+2,0,0,0,{100000,150000,0,0},5,3},
    {QT_TRANSLATE_NOOP("Materia_Names","Cover"),           {QT_TRANSLATE_NOOP("Materia_Skills","Cover +20%"),QT_TRANSLATE_NOOP("Materia_Skills","Cover +40%"),QT_TRANSLATE_NOOP("Materia_Skills","Cover +60%"),QT_TRANSLATE_NOOP("Materia_Skills","Cover +80%"),QT_TRANSLATE_NOOP("Materia_Skills","Cover +100%")},QT_TRANSLATE_NOOP("Materia_Stats","Vit:+1"), ":/icon/independent", 0x10,0,0,0,+1,0,0,0,0,{2000,10000,25000,40000},3,5},
    {QT_TRANSLATE_NOOP("Materia_Names","Underwater"),      {QT_TRANSLATE_NOOP("Materia_Skills","Underwater"),"","","",""},"", ":/icon/independent", 0x11,0,0,0,0,0,0,0,0,{0,0,0,0},3,1},
    {QT_TRANSLATE_NOOP("Materia_Names","HP <-> MP"),       {QT_TRANSLATE_NOOP("Materia_Skills","HP <-> MP"),QT_TRANSLATE_NOOP("Materia_Skills",""),"","",""},"", ":/icon/independent", 0x12,0,0,0,0,0,0,0,0,{80000,0,0,0},3,2},
    {QT_TRANSLATE_NOOP("Materia_Names","W-Magic"),         {QT_TRANSLATE_NOOP("Materia_Skills","W-Magic"),QT_TRANSLATE_NOOP("Materia_Skills",""),"","",""},"", ":/icon/command",     0x13,0,0,0,0,0,0,0,0,{250000,0,0,0},5,2},
    {QT_TRANSLATE_NOOP("Materia_Names","W-Summon"),        {QT_TRANSLATE_NOOP("Materia_Skills","W-Summon"),QT_TRANSLATE_NOOP("Materia_Skills",""),"","",""},"", ":/icon/command",     0x14,0,0,0,0,0,0,0,0,{250000,0,0,0},5,2},
    {QT_TRANSLATE_NOOP("Materia_Names","W-Item"),          {QT_TRANSLATE_NOOP("Materia_Skills","W-Item"),QT_TRANSLATE_NOOP("Materia_Skills",""),"","",""},"", ":/icon/command",     0x15,0,0,0,0,0,0,0,0,{250000,0,0,0},5,2},
    {QT_TRANSLATE_NOOP("Materia_Names","DON'T USE"),       {"?","?","?","?","?"},"ID:0x16", "",                   0X16,0,0,0,0,0,0,0,0,{0,0,0,0},0,0},
    {QT_TRANSLATE_NOOP("Materia_Names","All"),             {QT_TRANSLATE_NOOP("Materia_Skills","All x1"),QT_TRANSLATE_NOOP("Materia_Skills","All x2"),QT_TRANSLATE_NOOP("Materia_Skills","All x3"),QT_TRANSLATE_NOOP("Materia_Skills","All x4"),QT_TRANSLATE_NOOP("Materia_Skills","All x5")},"", ":/icon/support",     0x17,0,0,0,0,0,0,0,0,{1500,6000,18000,35000},4,5},
    {QT_TRANSLATE_NOOP("Materia_Names","Counter"),         {QT_TRANSLATE_NOOP("Materia_Skills","Counter Rate 20%"),QT_TRANSLATE_NOOP("Materia_Skills","Counter Rate 40%"),QT_TRANSLATE_NOOP("Materia_Skills","Counter Rate 60%"),QT_TRANSLATE_NOOP("Materia_Skills","Counter Rate 80%"),QT_TRANSLATE_NOOP("Materia_Skills","Counter Rate 100%")},"", ":/icon/support",     0x18,0,0,0,0,0,0,0,0,{20000,40000,60000,100000},4,5},
    {QT_TRANSLATE_NOOP("Materia_Names","Magic Counter"),   {QT_TRANSLATE_NOOP("Materia_Skills","Magic Counter Rate 30%"),QT_TRANSLATE_NOOP("Materia_Skills","Magic Counter Rate 40%"),QT_TRANSLATE_NOOP("Materia_Skills","Magic Counter Rate 60%"),QT_TRANSLATE_NOOP("Materia_Skills","Magic Counter Rate 80%"),QT_TRANSLATE_NOOP("Materia_Skills","Magic Counter Rate 100%")},"", ":/icon/support",     0x19,0,0,0,0,0,0,0,0,{20000,40000,80000,300000},4,5},
    {QT_TRANSLATE_NOOP("Materia_Names","MP Turbo"),        {QT_TRANSLATE_NOOP("Materia_Skills","MP Turbo 10%"),QT_TRANSLATE_NOOP("Materia_Skills","Mp Turbo 20%"),QT_TRANSLATE_NOOP("Materia_Skills","Mp Turbo 30%"),QT_TRANSLATE_NOOP("Materia_Skills","Mp Turbo 40%"),QT_TRANSLATE_NOOP("Materia_Skills","Mp Turbo 50%")},"", ":/icon/support",     0x1A,0,0,0,0,0,0,0,0,{10000,30000,60000,120000},4,5},
    {QT_TRANSLATE_NOOP("Materia_Names","MP Absorb"),       {QT_TRANSLATE_NOOP("Materia_Skills","MP Absorb"),QT_TRANSLATE_NOOP("Materia_Skills",""),"","",""},"", ":/icon/support",     0x1B,0,0,0,0,0,0,0,0,{100000,0,0,0},4,2},
    {QT_TRANSLATE_NOOP("Materia_Names","HP Absorb"),       {QT_TRANSLATE_NOOP("Materia_Skills","HP Absorb"),QT_TRANSLATE_NOOP("Materia_Skills",""),"","",""},"", ":/icon/support",     0x1C,0,0,0,0,0,0,0,0,{100000,0,0,0},4,2},
    {QT_TRANSLATE_NOOP("Materia_Names","Elemental"),       {QT_TRANSLATE_NOOP("Materia_Skills","Elemental 50%"),QT_TRANSLATE_NOOP("Materia_Skills","Elemental 100%"),QT_TRANSLATE_NOOP("Materia_Skills","Elemental 200%"),QT_TRANSLATE_NOOP("Materia_Skills",""),""},"", ":/icon/support",     0x1D,0,0,0,0,0,0,0,0,{10000,40000,80000,0},4,4},
    {QT_TRANSLATE_NOOP("Materia_Names","Added Effect"),    {QT_TRANSLATE_NOOP("Materia_Skills","Added Effect"),QT_TRANSLATE_NOOP("Materia_Skills",""),"","",""},"", ":/icon/support",     0x1E,0,0,0,0,0,0,0,0,{100000,0,0,0},4,2},
    {QT_TRANSLATE_NOOP("Materia_Names","Sneak Attack"),    {QT_TRANSLATE_NOOP("Materia_Skills","Sneak Attack 20%"),QT_TRANSLATE_NOOP("Materia_Skills","Sneak Attack 35%"),QT_TRANSLATE_NOOP("Materia_Skills","Sneak Attack 50%"),QT_TRANSLATE_NOOP("Materia_Skills","Sneak Attack 65%"),QT_TRANSLATE_NOOP("Materia_Skills","Sneak Attack 80%")},"", ":/icon/support",     0x1F,0,0,0,0,0,0,0,0,{20000,60000,100000,150000},4,5},
    {QT_TRANSLATE_NOOP("Materia_Names","Final Attack"),    {QT_TRANSLATE_NOOP("Materia_Skills","Final Attack x1"),QT_TRANSLATE_NOOP("Materia_Skills","Final Attack x2"),QT_TRANSLATE_NOOP("Materia_Skills","Final Attack x3"),QT_TRANSLATE_NOOP("Materia_Skills","Final Attack x4"),QT_TRANSLATE_NOOP("Materia_Skills","Final Attack x5")},"", ":/icon/support",     0x20,0,0,0,0,0,0,0,0,{20000,40000,80000,160000},4,5},
    {QT_TRANSLATE_NOOP("Materia_Names","Added Cut"),       {QT_TRANSLATE_NOOP("Materia_Skills","Added Cut"),QT_TRANSLATE_NOOP("Materia_Skills",""),"","",""},"", ":/icon/support",     0x21,0,0,0,0,0,0,0,0,{200000,0,0,0},4,2},
    {QT_TRANSLATE_NOOP("Materia_Names","Steal-As-Well"),   {QT_TRANSLATE_NOOP("Materia_Skills","Steal as well"),QT_TRANSLATE_NOOP("Materia_Skills",""),"","",""},"", ":/icon/support",     0x22,0,0,0,0,0,0,0,0,{200000,0,0,0},4,2},
    {QT_TRANSLATE_NOOP("Materia_Names","Quadra Magic"),    {QT_TRANSLATE_NOOP("Materia_Skills","Quadra Magic x1"),QT_TRANSLATE_NOOP("Materia_Skills","Quadra Magic x2"),QT_TRANSLATE_NOOP("Materia_Skills","Quadra Magic x3"),QT_TRANSLATE_NOOP("Materia_Skills","Quadra Magic x4"),QT_TRANSLATE_NOOP("Materia_Skills","Quadra Magic x5")},"", ":/icon/support",     0x23,0,0,0,0,0,0,0,0,{40000,80000,120000,200000},4,5},
    {QT_TRANSLATE_NOOP("Materia_Names","Steal"),           {QT_TRANSLATE_NOOP("Materia_Skills","Steal"),QT_TRANSLATE_NOOP("Materia_Skills","Mug"),QT_TRANSLATE_NOOP("Materia_Skills",""),"",""},QT_TRANSLATE_NOOP("Materia_Stats","Dex:+2"), ":/icon/command",     0x24,0,0,0,0,+2,0,0,0,{40000,50000,0,0},5,3},
    {QT_TRANSLATE_NOOP("Materia_Names","Sense"),           {QT_TRANSLATE_NOOP("Materia_Skills","Sense"),QT_TRANSLATE_NOOP("Materia_Skills",""),"","",""},"", ":/icon/command",     0x25,0,0,0,0,0,0,0,0,{40000,0,0,0},5,2},
    {QT_TRANSLATE_NOOP("Materia_Names","DON'T USE"),       {"?","?","?","?","?"},"ID:0x26", "" ,                  0X26,0,0,0,0,0,0,0,0,{0,0,0,0},0,0},
    {QT_TRANSLATE_NOOP("Materia_Names","Throw"),           {QT_TRANSLATE_NOOP("Materia_Skills","Throw"),QT_TRANSLATE_NOOP("Materia_Skills","Coin"),QT_TRANSLATE_NOOP("Materia_Skills",""),"",""},QT_TRANSLATE_NOOP("Materia_Stats","Vit:+1"), ":/icon/command",     0x27,0,0,0,+1,0,0,0,0,{45000,60000,0,0},5,3},
    {QT_TRANSLATE_NOOP("Materia_Names","Morph"),           {QT_TRANSLATE_NOOP("Materia_Skills","Morph"),QT_TRANSLATE_NOOP("Materia_Skills",""),"","",""},"", ":/icon/command",     0x28,0,0,0,0,0,0,0,0,{100000,0,0,0},5,2},
    {QT_TRANSLATE_NOOP("Materia_Names","Deathblow"),       {QT_TRANSLATE_NOOP("Materia_Skills","DeathBlow"),QT_TRANSLATE_NOOP("Materia_Skills",""),"","",""},QT_TRANSLATE_NOOP("Materia_Stats","Lck:+1"), ":/icon/command",     0x29,0,0,0,0,0,+1,0,0,{40000,0,0,0},5,2},
    {QT_TRANSLATE_NOOP("Materia_Names","Manipulate"),      {QT_TRANSLATE_NOOP("Materia_Skills","Manipulate"),QT_TRANSLATE_NOOP("Materia_Skills",""),"","",""},"", ":/icon/command",     0x2A,0,0,0,0,0,0,0,0,{40000,0,0,0},5,2},
    {QT_TRANSLATE_NOOP("Materia_Names","Mime"),            {QT_TRANSLATE_NOOP("Materia_Skills","Mime"),QT_TRANSLATE_NOOP("Materia_Skills",""),"","",""},"", ":/icon/command",     0x2B,0,0,0,0,0,0,0,0,{100000,0,0,0},5,2},
    {QT_TRANSLATE_NOOP("Materia_Names","Enemy Skill"),     {QT_TRANSLATE_NOOP("Materia_Skills","Enemy Skill"),"","","",""},"", ":/icon/command",     0x2C,0,0,0,0,0,0,0,0,{0,0,0,0},5,1},
    {QT_TRANSLATE_NOOP("Materia_Names","DON'T USE"),       {"?","?","?","?","?"},"ID:0x2D", "",                   0X2D,0,0,0,0,0,0,0,0,{0,0,0,0},0,0},
    {QT_TRANSLATE_NOOP("Materia_Names","DON'T USE"),       {"?","?","?","?","?"},"ID:0x2E", "",                   0X2E,0,0,0,0,0,0,0,0,{0,0,0,0},0,0},
    {QT_TRANSLATE_NOOP("Materia_Names","DON'T USE"),       {"?","?","?","?","?"},"ID:0x2F", "",                   0X2F,0,0,0,0,0,0,0,0,{0,0,0,0},0,0},
    {QT_TRANSLATE_NOOP("Materia_Names","Master Command"),  {QT_TRANSLATE_NOOP("Materia_Skills","Master Command"),"","","",""},"", ":/icon/command",     0x30,0,0,0,0,0,0,0,0,{0,0,0,0},5,1},
    {QT_TRANSLATE_NOOP("Materia_Names","Fire"),            {QT_TRANSLATE_NOOP("Materia_Skills","Fire (4mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Fire2 (22mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Fire3 (52mp)"),QT_TRANSLATE_NOOP("Materia_Skills",""),""},QT_TRANSLATE_NOOP("Materia_Stats","MaxHp:-2% MaxMp:+2% Str:-1 Mag:+1"), ":/icon/magic",       0x31,-2,+2,-1,0,0,0,+1,0,{2000,18000,35000,0},1,4},
    {QT_TRANSLATE_NOOP("Materia_Names","Ice"),             {QT_TRANSLATE_NOOP("Materia_Skills","Ice (4mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Ice2 (22mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Ice3 (52mp)"),QT_TRANSLATE_NOOP("Materia_Skills",""),""},QT_TRANSLATE_NOOP("Materia_Stats","MaxHp:-2% MaxMp:+2% Str:-1 Mag:+1"), ":/icon/magic",       0x32,-2,+2,-1,0,0,0,+1,0,{2000,18000,35000,0},1,4},
    {QT_TRANSLATE_NOOP("Materia_Names","Earth"),           {QT_TRANSLATE_NOOP("Materia_Skills","Quake (6mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Quake2 (28mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Quake3 (68mp)"),QT_TRANSLATE_NOOP("Materia_Skills",""),""},QT_TRANSLATE_NOOP("Materia_Stats","MaxHp:-2% MaxMp:+2% Str:-1 Mag:+1"), ":/icon/magic",       0x33,-2,+2,-1,0,0,0,+1,0,{6000,22000,40000,0},1,4},
    {QT_TRANSLATE_NOOP("Materia_Names","Lightning"),       {QT_TRANSLATE_NOOP("Materia_Skills","Bolt (4mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Bolt2 (22mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Bolt3 (52mp)"),QT_TRANSLATE_NOOP("Materia_Skills",""),""},QT_TRANSLATE_NOOP("Materia_Stats","MaxHp:-2% MaxMp:+2% Str:-1 Mag:+1"), ":/icon/magic",       0x34,-2,+2,-1,0,0,0,+1,0,{2000,18000,35000,0},1,4},
    {QT_TRANSLATE_NOOP("Materia_Names","Restore"),         {QT_TRANSLATE_NOOP("Materia_Skills","Cure (5mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Cure2 (24mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Regen (30mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Cure3 (64mp)"),QT_TRANSLATE_NOOP("Materia_Skills","")},QT_TRANSLATE_NOOP("Materia_Stats","MaxHp:-2% MaxMp:+2% Str:-1 Mag:+1"), ":/icon/magic",       0x35,-2,+2,-1,0,0,0,+1,0,{2500,17000,25000,40000},1,5},
    {QT_TRANSLATE_NOOP("Materia_Names","Heal"),            {QT_TRANSLATE_NOOP("Materia_Skills","Poisona (3mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Esuna (15mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Resist (120mp)"),QT_TRANSLATE_NOOP("Materia_Skills",""),""},QT_TRANSLATE_NOOP("Materia_Stats","MaxHp:-2% MaxMp:+2% Str:-1 Mag:+1"), ":/icon/magic",       0x36,-2,+2,-1,0,0,0,+1,0,{12000,52000,60000,0},1,4},
    {QT_TRANSLATE_NOOP("Materia_Names","Revive"),          {QT_TRANSLATE_NOOP("Materia_Skills","Life (34mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Life2 (100mp)"),QT_TRANSLATE_NOOP("Materia_Skills",""),"",""},QT_TRANSLATE_NOOP("Materia_Stats","MaxHp:-5% MaxMp:+5% Str:-2 Vit:-1 Mag:+2 Spi:+1"), ":/icon/magic",       0x37,-5,+5,-2,-1,0,0,+2,+1,{45000,55000,0,0},1,3},
    {QT_TRANSLATE_NOOP("Materia_Names","Seal"),            {QT_TRANSLATE_NOOP("Materia_Skills","Sleepel (8mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Silence (24mp)"),QT_TRANSLATE_NOOP("Materia_Skills",""),"",""},QT_TRANSLATE_NOOP("Materia_Stats","MaxHp:-2% MaxMp:+2% Str:-1 Mag:+1"), ":/icon/magic",       0x38,-2,+2,-1,0,0,0,+1,0,{10000,20000,0,0},1,3},
    {QT_TRANSLATE_NOOP("Materia_Names","Mystify"),         {QT_TRANSLATE_NOOP("Materia_Skills","Confu (18mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Berserk (28mp)"),QT_TRANSLATE_NOOP("Materia_Skills",""),"",""},QT_TRANSLATE_NOOP("Materia_Stats","MaxHp:-2% MaxMp:+2% Str:-1 Mag:+1"), ":/icon/magic",       0x39,-2,+2,-1,0,0,0,+1,0,{12000,25000,0,0},1,3},
    {QT_TRANSLATE_NOOP("Materia_Names","Transform"),       {QT_TRANSLATE_NOOP("Materia_Skills","Mini (10mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Toad (14mp)"),QT_TRANSLATE_NOOP("Materia_Skills",""),"",""},QT_TRANSLATE_NOOP("Materia_Stats","MaxHp:-2% MaxMp:+2% Str:-1 Mag:+1"), ":/icon/magic",       0x3A,-2,+2,-1,0,0,0,+1,0,{8000,24000,0,0},1,3},
    {QT_TRANSLATE_NOOP("Materia_Names","Exit"),            {QT_TRANSLATE_NOOP("Materia_Skills","Exit (16mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Remove (99mp)"),QT_TRANSLATE_NOOP("Materia_Skills",""),"",""},QT_TRANSLATE_NOOP("Materia_Stats","MaxHp:-2% MaxMp:+2% Str:-1 Mag:+1"), ":/icon/magic",       0x3B,-2,+2,-1,0,0,0,+1,0,{10000,30000,0,0},1,3},
    {QT_TRANSLATE_NOOP("Materia_Names","Poison"),          {QT_TRANSLATE_NOOP("Materia_Skills","Bio (8mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Bio2 (36mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Bio3 (80mp)"),QT_TRANSLATE_NOOP("Materia_Skills",""),""},QT_TRANSLATE_NOOP("Materia_Stats","MaxHp:-2% MaxMp:+2% Str:-1 Mag:+1"), ":/icon/magic",       0x3C,-2,+2,-1,0,0,0,+1,0,{5000,20000,38000,0},1,4},
    {QT_TRANSLATE_NOOP("Materia_Names","Gravity"),         {QT_TRANSLATE_NOOP("Materia_Skills","Demi (14mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Demi2 (33mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Demi3 (48mp)"),QT_TRANSLATE_NOOP("Materia_Skills",""),""},QT_TRANSLATE_NOOP("Materia_Stats","MaxHp:-2% MaxMp:+2% Str:-1 Mag:+1"), ":/icon/magic",       0x3D,-2,+2,-1,0,0,0,+1,0,{10000,20000,40000,0},1,4},
    {QT_TRANSLATE_NOOP("Materia_Names","Barrier"),         {QT_TRANSLATE_NOOP("Materia_Skills","Barrier (16mp)"),QT_TRANSLATE_NOOP("Materia_Skills","M-Barrier (24mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Reflect (30mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Wall (58mp)"),QT_TRANSLATE_NOOP("Materia_Skills","")},QT_TRANSLATE_NOOP("Materia_Stats","MaxHp:-5% MaxMp:+5% Str:-2 Vit:-1 Mag:+2 Spi:+1"), ":/icon/magic",       0x3E,-5,+5,-2,-1,0,0,+2,+1,{5000,15000,30000,45000},1,5},
    {QT_TRANSLATE_NOOP("Materia_Names","DON'T USE"),       {"?","?","?","?","?"},"ID:0x3F", "",                   0X3F,0,0,0,0,0,0,0,0,{0,0,0,0},0,0},
    {QT_TRANSLATE_NOOP("Materia_Names","Comet"),           {QT_TRANSLATE_NOOP("Materia_Skills","Comet (70mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Comet2 (110mp)"),QT_TRANSLATE_NOOP("Materia_Skills",""),"",""},QT_TRANSLATE_NOOP("Materia_Stats","MaxHp:-5% MaxMp:+5% Str:-2 Vit:-1 Mag:+2 Spi:+1"), ":/icon/magic",       0x40,-5,+5,-2,-1,0,0,+2,+1,{12000,60000,0,0},1,3},
    {QT_TRANSLATE_NOOP("Materia_Names","Time"),            {QT_TRANSLATE_NOOP("Materia_Skills","Haste (18mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Slow (20mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Stop (34mp)"),QT_TRANSLATE_NOOP("Materia_Skills",""),""},QT_TRANSLATE_NOOP("Materia_Stats","MaxHp:-5% MaxMp:+5% Str:-2 Vit:-1 Mag:+2 Spi:+1"), ":/icon/magic",       0x41,-5,+5,-2,-1,0,0,+2,+1,{10000,20000,42000,0},1,4},
    {QT_TRANSLATE_NOOP("Materia_Names","DON'T USE"),       {"?","?","?","?","?"},"ID:0x42", "",                   0X42,0,0,0,0,0,0,0,0,{0,0,0,0},0,0},
    {QT_TRANSLATE_NOOP("Materia_Names","DON'T USE"),       {"?","?","?","?","?"},"ID:0x43", "",                   0X43,0,0,0,0,0,0,0,0,{0,0,0,0},0,0},
    {QT_TRANSLATE_NOOP("Materia_Names","Destruct"),        {QT_TRANSLATE_NOOP("Materia_Skills","DeBarrier (12mp)"),QT_TRANSLATE_NOOP("Materia_Skills","DeSpell (20mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Death (30mp)"),QT_TRANSLATE_NOOP("Materia_Skills",""),""},QT_TRANSLATE_NOOP("Materia_Stats","MaxHp:-5% MaxMp:+5% Str:-2 Vit:-1 Mag:+2 Spi:+1"), ":/icon/magic",       0x44,-5,+5,-2,-1,0,0,+2,+1,{6000,10000,45000,0},1,4},
    {QT_TRANSLATE_NOOP("Materia_Names","Contain"),         {QT_TRANSLATE_NOOP("Materia_Skills","Freeze (82mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Break (86mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Tornado (90mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Flare (100mp)"),QT_TRANSLATE_NOOP("Materia_Skills","")},QT_TRANSLATE_NOOP("Materia_Stats","MaxHp:-10% MaxMp:+10% Str:-4 Vit:-2 Mag:+4 Spi:+2"), ":/icon/magic",       0x45,-10,+10,-4,-2,0,0,+4,+2,{5000,10000,15000,60000},1,5},
    {QT_TRANSLATE_NOOP("Materia_Names","FullCure"),        {"",QT_TRANSLATE_NOOP("Materia_Skills","Full Cure (99mp)"),QT_TRANSLATE_NOOP("Materia_Skills",""),"",""},QT_TRANSLATE_NOOP("Materia_Stats","MaxHp:-10% MaxMp:+10% Str:-4 Vit:-2 Mag:+4 Spi:+2"), ":/icon/magic",       0x46,-10,+10,-4,-2,0,0,+4,+2,{3000,100000,0,0},1,3},
    {QT_TRANSLATE_NOOP("Materia_Names","Shield"),          {"",QT_TRANSLATE_NOOP("Materia_Skills","Shield (180mp)"),QT_TRANSLATE_NOOP("Materia_Skills",""),"",""},QT_TRANSLATE_NOOP("Materia_Stats","MaxHp:-10% MaxMp:+10% Str:-4 Vit:-2 Mag:+4 Spi:+2"), ":/icon/magic",       0x47,-10,+10,-4,-2,0,0,+4,+2,{10000,100000,0,0},1,3},
    {QT_TRANSLATE_NOOP("Materia_Names","Ultima"),          {"",QT_TRANSLATE_NOOP("Materia_Skills","Ultima (130mp)"),QT_TRANSLATE_NOOP("Materia_Skills",""),"",""},QT_TRANSLATE_NOOP("Materia_Stats","MaxHp:-10% MaxMp:+10% Str:-4 Vit:-2 Mag:+4 Spi:+2"), ":/icon/magic",       0x48,-10,+10,-4,-2,0,0,+4,+2,{5000,100000,0,0},1,3},
    {QT_TRANSLATE_NOOP("Materia_Names","Master Magic"),    {QT_TRANSLATE_NOOP("Materia_Skills","Master Magic"),"","","",""},"", ":/icon/magic",       0x49,0,0,0,0,0,0,0,0,{0,0,0,0},1,1},
    {QT_TRANSLATE_NOOP("Materia_Names","Choco/Mog"),       {QT_TRANSLATE_NOOP("Materia_Skills","Choco/Mog x1 (14mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Choco/Mog x2 (14mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Choco/Mog x3 (14mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Choco/Mog x4 (14mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Choco/Mog x5 (14mp)")},QT_TRANSLATE_NOOP("Materia_Stats","MaxHp:-2% MaxMp:+2% Mag:+1"), ":/icon/summon",      0x4A,-2,+2,0,0,0,0,+1,0,{2000,14000,25000,35000},2,5},
    {QT_TRANSLATE_NOOP("Materia_Names","Shiva"),           {QT_TRANSLATE_NOOP("Materia_Skills","Shiva x1 (32mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Shiva x2 (32mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Shiva x3 (32mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Shiva x4 (32mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Shiva x5 (32mp)")},QT_TRANSLATE_NOOP("Materia_Stats","MaxHp:-2% MaxMp:+2% Mag:+1"), ":/icon/summon",      0x4B,-2,+2,0,0,0,0,+1,0,{4000,15000,30000,50000},2,5},
    {QT_TRANSLATE_NOOP("Materia_Names","Ifrit"),           {QT_TRANSLATE_NOOP("Materia_Skills","Ifrit x1 (34mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Ifrit x2 (34mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Ifrit x3 (34mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Ifrit x4 (34mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Ifrit x5 (34mp)")},QT_TRANSLATE_NOOP("Materia_Stats","MaxHp:-2% MaxMp:+2% Mag:+1"), ":/icon/summon",      0x4C,-2,+2,0,0,0,0,+1,0,{5000,20000,35000,60000},2,5},
    {QT_TRANSLATE_NOOP("Materia_Names","Ramuh"),           {QT_TRANSLATE_NOOP("Materia_Skills","Ramuh x1 (40mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Ramuh x2 (40mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Ramuh x3 (40mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Ramuh x4 (40mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Ramuh x5 (40mp)")},QT_TRANSLATE_NOOP("Materia_Stats","MaxHp:-2% MaxMp:+2% Mag:+1"), ":/icon/summon",      0x4D,-2,+2,0,0,0,0,+1,0,{10000,25000,50000,70000},2,5},
    {QT_TRANSLATE_NOOP("Materia_Names","Titan"),           {QT_TRANSLATE_NOOP("Materia_Skills","Titan x1 (46mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Titan x2 (46mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Titan x3 (46mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Titan x4 (46mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Titan x5 (46mp)")},QT_TRANSLATE_NOOP("Materia_Stats","MaxHp:-2% MaxMp:+2% Mag:+1"), ":/icon/summon",      0x4E,-2,+2,0,0,0,0,+1,0,{15000,30000,60000,80000},2,5},
    {QT_TRANSLATE_NOOP("Materia_Names","Odin"),            {QT_TRANSLATE_NOOP("Materia_Skills","Odin x1 (80mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Odin x2 (80mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Odin x3 (80mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Odin x4 (80mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Odin x5 (80mp)")},QT_TRANSLATE_NOOP("Materia_Stats","MaxHp:-5% MaxMp:+5% Mag:+1 Spi:+1"), ":/icon/summon",      0x4F,-5,+5,0,0,0,0,+1,+1,{16000,32000,65000,90000},2,5},
    {QT_TRANSLATE_NOOP("Materia_Names","Leviathan"),       {QT_TRANSLATE_NOOP("Materia_Skills","Leviathan x1 (78mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Leviathan x2 (78mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Leviathan x3 (78mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Leviathan x4 (78mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Leviathan x5 (78mp)")},QT_TRANSLATE_NOOP("Materia_Stats","MaxHp:-5% MaxMp:+5% Mag:+1 Spi:+1"), ":/icon/summon",      0x50,-5,+5,0,0,0,0,+1,+1,{18000,38000,70000,100000},2,5},
    {QT_TRANSLATE_NOOP("Materia_Names","Bahamut"),         {QT_TRANSLATE_NOOP("Materia_Skills","Bahamut x1 (100mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Bahamut x2 (100mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Bahamut x3 (100mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Bahamut x4 (100mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Bahamut x5 (100mp)")},QT_TRANSLATE_NOOP("Materia_Stats","MaxHp:-5% MaxMp:+5% Mag:+1 Spi:+1"), ":/icon/summon",      0x51,-5,+5,0,0,0,0,+1,+1,{20000,50000,80000,120000},2,5},
    {QT_TRANSLATE_NOOP("Materia_Names","Kujata"),          {QT_TRANSLATE_NOOP("Materia_Skills","Kujata x1 (110mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Kujata x2 (110mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Kujata x3 (110mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Kujata x4 (110mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Kujata x5 (110mp)")},QT_TRANSLATE_NOOP("Materia_Stats","MaxHp:-5% MaxMp:+5% Mag:+1 Spi:+1"), ":/icon/summon",      0x52,-5,+5,0,0,0,0,+1,+1,{22000,60000,90000,140000},2,5},
    {QT_TRANSLATE_NOOP("Materia_Names","Alexander"),       {QT_TRANSLATE_NOOP("Materia_Skills","Alexander x1 (120mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Alexander x2 (120mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Alexander x3 (120mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Alexander x4 (120mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Alexander x5 (120mp)")},QT_TRANSLATE_NOOP("Materia_Stats","MaxHp:-5% MaxMp:+5% Mag:+1 Spi:+1"), ":/icon/summon",      0x53,-5,+5,0,0,0,0,+1,+1,{25000,65000,100000,150000},2,5},
    {QT_TRANSLATE_NOOP("Materia_Names","Phoenix"),         {QT_TRANSLATE_NOOP("Materia_Skills","Phoenix x1 (180mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Phoenix x2 (180mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Phoenix x3 (180mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Phoenix x4 (180mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Phoenix x5 (180mp)")},QT_TRANSLATE_NOOP("Materia_Stats","MaxHp:-10% MaxMp:+10% Mag:+2 Spi:+2"), ":/icon/summon",      0x54,-10,+10,0,0,0,0,+2,+2,{28000,70000,120000,180000},2,5},
    {QT_TRANSLATE_NOOP("Materia_Names","Neo Bahamut"),     {QT_TRANSLATE_NOOP("Materia_Skills","Neo Bahamut x1 (140mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Neo Bahamut x2 (140mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Neo Bahamut x3 (140mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Neo Bahamut x4 (140mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Neo Bahamut x5 (140mp)")},QT_TRANSLATE_NOOP("Materia_Stats","MaxHp:-10% MaxMp:+10% Mag:+2 Spi:+2"), ":/icon/summon",      0x55,-10,+10,0,0,0,0,+2,+2,{30000,80000,140000,200000},2,5},
    {QT_TRANSLATE_NOOP("Materia_Names","Hades"),           {QT_TRANSLATE_NOOP("Materia_Skills","Hades x1 (150mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Hades x2 (150mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Hades x3 (150mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Hades x4 (150mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Hades x5 (150mp)")},QT_TRANSLATE_NOOP("Materia_Stats","MaxHp:-10% MaxMp:+15% Mag:+4 Spi:+4"), ":/icon/summon",      0x56,-10,+15,0,0,0,0,+4,+4,{35000,120000,150000,250000},2,5},
    {QT_TRANSLATE_NOOP("Materia_Names","Typhon"),          {QT_TRANSLATE_NOOP("Materia_Skills","Typhon x1 (160mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Typhon x2 (160mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Typhon x3 (160mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Typhon x4 (160mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Typhon x5 (160mp)")},QT_TRANSLATE_NOOP("Materia_Stats","MaxHp:-10% MaxMp:+15% Mag:+4 Spi:+4"), ":/icon/summon",      0x57,-10,+15,0,0,0,0,+4,+4,{35000,120000,150000,250000},2,5},
    {QT_TRANSLATE_NOOP("Materia_Names","Bahamut ZERO"),    {QT_TRANSLATE_NOOP("Materia_Skills","Bahamut ZERO x1 (180mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Bahamut ZERO x2 (180mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Bahamut ZERO x3 (180mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Bahamut ZERO x4 (180mp)"),QT_TRANSLATE_NOOP("Materia_Skills","Bahamut ZERO x5 (180mp)")},QT_TRANSLATE_NOOP("Materia_Stats","MaxHp:-10% MaxMp:+15% Mag:+4 Spi:+4"), ":/icon/summon",      0x58,-10,+15,0,0,0,0,+4,+4,{35000,120000,150000,250000},2,5},
    {QT_TRANSLATE_NOOP("Materia_Names","Knights of Round"),{QT_TRANSLATE_NOOP("Materia_Skills","KOTR x1 (250mp)"),QT_TRANSLATE_NOOP("Materia_Skills","KOTR x2 (250mp)"),QT_TRANSLATE_NOOP("Materia_Skills","KOTR x3 (250mp)"),QT_TRANSLATE_NOOP("Materia_Skills","KOTR x4 (250mp)"),QT_TRANSLATE_NOOP("Materia_Skills","KOTR x5 (250mp)")},QT_TRANSLATE_NOOP("Materia_Stats","MaxHp:-10% MaxMp:+20% Mag:+8 Spi:+8"), ":/icon/summon",      0x59,-10,+20,0,0,0,0,+8,+8,{50000,200000,300000,500000},2,5},
    {QT_TRANSLATE_NOOP("Materia_Names","Master Summon"),   {QT_TRANSLATE_NOOP("Materia_Skills","Master Summon"),"","","",""},"", ":/icon/summon",      0x5A,0,0,0,0,0,0,0,0,{0,0,0,0},2,1}
};
#endif //FF7STATICDATA._H
