#############################################################################
# Makefile for building: Black_Chocobo
# Generated by qmake (2.01a) (Qt 4.7.0) on: Sun Dec 12 12:09:16 2010
# Project:  Black_Chocobo.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile Black_Chocobo.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		slotselect.cpp \
		globals.cpp \
		about.cpp \
		options.cpp moc_mainwindow.cpp \
		moc_slotselect.cpp \
		moc_about.cpp \
		moc_options.cpp \
		qrc_images.cpp
OBJECTS       = main.o \
		mainwindow.o \
		slotselect.o \
		globals.o \
		about.o \
		options.o \
		moc_mainwindow.o \
		moc_slotselect.o \
		moc_about.o \
		moc_options.o \
		qrc_images.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		Black_Chocobo.pro
QMAKE_TARGET  = Black_Chocobo
DESTDIR       = 
TARGET        = Black_Chocobo

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h ui_slotselect.h ui_about.h ui_options.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Black_Chocobo.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -o Makefile Black_Chocobo.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile Black_Chocobo.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Black_Chocobo1.0.0 || $(MKDIR) .tmp/Black_Chocobo1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Black_Chocobo1.0.0/ && $(COPY_FILE) --parents mainwindow.h FF7SAVE.h slotselect.h about.h globals.h options.h .tmp/Black_Chocobo1.0.0/ && $(COPY_FILE) --parents images.qrc .tmp/Black_Chocobo1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp slotselect.cpp globals.cpp about.cpp options.cpp .tmp/Black_Chocobo1.0.0/ && $(COPY_FILE) --parents mainwindow.ui slotselect.ui about.ui options.ui .tmp/Black_Chocobo1.0.0/ && $(COPY_FILE) --parents lang/bchoco_en.ts lang/bchoco_es.ts lang/bchoco_fr.ts .tmp/Black_Chocobo1.0.0/ && (cd `dirname .tmp/Black_Chocobo1.0.0` && $(TAR) Black_Chocobo1.0.0.tar Black_Chocobo1.0.0 && $(COMPRESS) Black_Chocobo1.0.0.tar) && $(MOVE) `dirname .tmp/Black_Chocobo1.0.0`/Black_Chocobo1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Black_Chocobo1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_slotselect.cpp moc_about.cpp moc_options.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_slotselect.cpp moc_about.cpp moc_options.cpp
moc_mainwindow.cpp: mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_slotselect.cpp: slotselect.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) slotselect.h -o moc_slotselect.cpp

moc_about.cpp: about.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) about.h -o moc_about.cpp

moc_options.cpp: options.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) options.h -o moc_options.cpp

compiler_rcc_make_all: qrc_images.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_images.cpp
qrc_images.cpp: images.qrc \
		icon/clip.png \
		icon/cait.png \
		icon/2.png \
		icon/14.png \
		icon/psxmc.png \
		icon/yuffie.png \
		icon/fr.png \
		icon/2_unsel.png \
		icon/6.png \
		icon/config.png \
		icon/tifa.png \
		icon/jp.png \
		icon/5_unsel.png \
		icon/eu_unsel.png \
		icon/b_m_s_e.png \
		icon/debug.png \
		icon/vincent.png \
		icon/y_m_s_f.png \
		icon/exportmc.png \
		icon/11.png \
		icon/8_unsel.png \
		icon/staff.png \
		icon/i_materia.png \
		icon/11_unsel.png \
		icon/cid.png \
		icon/star.png \
		icon/accessory.png \
		icon/blue_choco.png \
		icon/import.png \
		icon/y_m_s_e.png \
		icon/a_materia.png \
		icon/3.png \
		icon/15.png \
		icon/14_unsel.png \
		icon/next.png \
		icon/us.png \
		icon/s_materia.png \
		icon/us_unsel.png \
		icon/debug_unsel.png \
		icon/paste.png \
		icon/glove.png \
		icon/7.png \
		icon/mphone.png \
		icon/c_materia.png \
		icon/slot_sel.png \
		icon/cloud.png \
		icon/g_m_s_e.png \
		icon/3_unsel.png \
		icon/es_unsel.png \
		icon/save.png \
		icon/default_save.png \
		icon/12.png \
		icon/qt_logo.png \
		icon/import_char.png \
		icon/6_unsel.png \
		icon/eu.png \
		icon/red.png \
		icon/r_m_s_f.png \
		icon/sep.png \
		icon/quit.png \
		icon/armor.png \
		icon/g_m_s_f.png \
		icon/9_unsel.png \
		icon/exportpc.png \
		icon/4.png \
		icon/green_choco.png \
		icon/sword.png \
		icon/gunarm.png \
		icon/12_unsel.png \
		icon/export_char.png \
		icon/de_unsel.png \
		icon/delete.png \
		icon/15_unsel.png \
		icon/f_m_s_f.png \
		icon/8.png \
		icon/sup_materia.png \
		icon/gold_choco.png \
		icon/open.png \
		icon/export.png \
		icon/spear.png \
		icon/gun.png \
		icon/de.png \
		icon/m_materia.png \
		icon/black_choco.png \
		icon/1.png \
		icon/1_unsel.png \
		icon/13.png \
		icon/bchoco.png \
		icon/psn.png \
		icon/4_unsel.png \
		icon/r_m_s_e.png \
		icon/new_plus.png \
		icon/y_cloud.png \
		icon/5.png \
		icon/7_unsel.png \
		icon/fr_unsel.png \
		icon/aeris.png \
		icon/10_unsel.png \
		icon/item.png \
		icon/10.png \
		icon/previous.png \
		icon/9.png \
		icon/yellow_choco.png \
		icon/13_unsel.png \
		icon/barret.png \
		icon/b_m_s_f.png \
		icon/es.png \
		icon/copy.png \
		icon/jp_unsel.png \
		icon/f_m_s_e.png
	/usr/bin/rcc -name images images.qrc -o qrc_images.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_slotselect.h ui_about.h ui_options.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_slotselect.h ui_about.h ui_options.h
ui_mainwindow.h: mainwindow.ui
	/usr/bin/uic-qt4 mainwindow.ui -o ui_mainwindow.h

ui_slotselect.h: slotselect.ui
	/usr/bin/uic-qt4 slotselect.ui -o ui_slotselect.h

ui_about.h: about.ui
	/usr/bin/uic-qt4 about.ui -o ui_about.h

ui_options.h: options.ui
	/usr/bin/uic-qt4 options.ui -o ui_options.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		ui_mainwindow.h \
		globals.h \
		FF7SAVE.h \
		slotselect.h \
		options.h \
		about.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

slotselect.o: slotselect.cpp slotselect.h \
		ui_slotselect.h \
		globals.h \
		FF7SAVE.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o slotselect.o slotselect.cpp

globals.o: globals.cpp globals.h \
		FF7SAVE.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o globals.o globals.cpp

about.o: about.cpp about.h \
		ui_about.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o about.o about.cpp

options.o: options.cpp options.h \
		ui_options.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o options.o options.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_slotselect.o: moc_slotselect.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_slotselect.o moc_slotselect.cpp

moc_about.o: moc_about.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_about.o moc_about.cpp

moc_options.o: moc_options.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_options.o moc_options.cpp

qrc_images.o: qrc_images.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_images.o qrc_images.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

