#! /bin/bash -e
#DEBHELPER#
echo -e "Checking for and removing old install...\c"
if [ -d /opt/blackchocobo ];then 
  rm -r /opt/blackchocobo
  echo "RM: /opt/blackchocobo"
else echo "Not Found"
fi

if [ -f /usr/share/blackchocobo/Black_Chocobo ];then 
  rm /usr/share/blackchocobo/Black_Chocobo
fi
