#! /bin/sh
echo "Checking for and removing old install...\c"
if [ -d /usr/bin/blackchocobo ];then #check to see if older version installed.
  rm -r /usr/bin/blackchocobo/
  echo "RM:/usr/bin/blackchcobo"
elif [ -d /opt/blackchocobo ];then 
  rm -r /opt/blackchocobo
  echo "RM: /opt/blackchocobo"
else echo 'Not Found'
fi
