//This file was generated by CMake.
#include <QString>

/**
 * @brief Get the version of ff7tk in use
 * @return: Version of ff7tk
*/
QString ff7tk_version() {
    QString version = QStringLiteral("0.80.17");
    if(!QString("ff31ba8").isEmpty())
        version.append(QStringLiteral("-ff31ba8"));
    return version;
}
