//This file was generated by CMake.
#include <QString>

/**
 * @brief Get the version of ff7tk in use
 * @return: Version of ff7tk
*/
QString ff7tk_version() {
    QString version = QStringLiteral("0.80.16");
    if(!QString("7db8071").isEmpty())
        version.append(QStringLiteral("-7db8071"));
    return version;
}
